//
//  DeadEnds Library
//
//  functable.c has the table of built-in functions in the DeadEnds scripting language.
//
//  Created by Thomas Wetmore on 10 January 2023.
//  Last changed on 3 June 2025.
//

#include <ansidecl.h>		/* ATTRIBUTE_UNUSED */
#include <stdint.h>

#include "standard.h"
#include "symboltable.h"
#include "gedcom.h"
#include "functiontable.h"
#include "pnode.h"
#include "interp.h"
#include "refnindex.h"
#include "errors.h"

#include "pnode.h"

#include "builtintable.h"

BuiltIn builtIns[] = {
  { "add",          2,    32,    __add },
  { "addnode",      2,    3,    __addnode },
  { "addtoset",     3,    3,    __addtoset },
  { "alpha",        1,    1,    __alpha },
  { "ancestorset",  1,    1,    __ancestorset },
  { "and",          2,    CC,    __and },
  { "append",        2,   2,    __append },
  { "atoi",         1,    1,    __strtoint },		// LL compatibility
  { "baptism",      1,    1,    __baptism },
  { "birth",        1,    1,    __birth },
  { "burial",       1,    1,    __burial },
  { "capitalize",   1,    1,    __capitalize },
  { "card",         1,    1,    __card },
  { "child",        1,    1,    __child },
  { "children",     1,    1,    __children },
  { "childset",     1,    1,    __childset },
//{ "choosechild",  1,    1,    __choosechild },
//{ "choosefam",    1,    1,    __choosefam },
//{ "chooseindi",   1,    1,    __chooseindi },
//{ "choosespouse", 1,    1,    __choosespouse },
//{ "choosesubset", 1,    1,    __choosesubset },
  { "col",          1,    1,    __col },
  { "concat",       1,    CC,   __concat },
  { "copyfile",     1,    1,    __copyfile },
  { "createnode",   1,    2,    __createnode },
  { "d",            1,    1,    __d },
  { "database",     0,    1,    __noop },
  { "date",         1,    1,    __date },
  { "dateformat",   1,    1,    __dateformat },
  { "dayformat",    1,    1,    __dayformat },
  { "death",        1,    1,    __death },
  { "decr",         1,    1,    __decr },
  { "deletefromset",3,    3,    __deletefromset },
  { "deletenode",   1,    1,    __deletenode },
  { "dequeue",      1,    1,    __removeLast },
  { "dereference",  1,    1,    __getrecord },
  { "descendantset",1,    1,    __descendentset },
  { "descendentset",1,    1,    __descendentset },
  { "detachnode",   1,    1,    __deletenode },
  { "difference",   2,    2,    __difference },
  { "div",          2,    2,    __div },
  { "empty",        1,    1,    __empty },
  { "enqueue",      2,    2,    __prepend },
  { "eq",           2,    2,    __eq },
  { "eqstr",        2,    2,    __eqstr },
  { "exp",          2,    2,    __exp },
  { "extractdate",  4,    4,    __extractdate },
  { "extractnames", 4,    4,    __extractnames },
  { "extractplaces",3,    3,    __extractplaces },
  { "extracttokens",4,    4,    __extracttokens },
  { "f",            1,    1,    __f },
  { "fam",          1,    1,    __fam },
  { "father",       1,    1,    __father },
  { "female",       1,    1,    __female },
  { "firstchild",   1,    1,    __firstchild },
  { "firstfam",     0,    0,    __firstfam },
  { "firstindi",    0,    0,    __firstindi },
  { "fnode",        1,    1,    __fnode },
  { "fullname",     4,    4,    __fullname },
  { "ge",           2,    2,    __ge },
  { "gengedcom",    1,    1,    __gengedcom },
//{ "genindiset",   2,    2,    __genindiset },
  { "getel",        2,    2,    __getel },
  { "getfam",       1,    1,    __getfam },
  { "getindi",      1,    2,    __getindi },
//{ "getindimsg",   2,    2,    __getindi },
//{ "getindiset",   1,    2,    __getindiset },
  { "getint",       1,    2,    __getint },
//{ "getintmsg",    2,    2,    __getint },
  { "getproperty",  1,    1,    __getproperty },
  { "getrecord",    1,    1,    __getrecord },
  { "getstr",       1,    2,    __getstr },
//{ "getstrmsg",    2,    2,    __getstr },
  { "gettoday",     0,    0,    __gettoday },
  { "givens",       1,    1,    __givens },
  { "gt",           2,    2,    __gt },
  { "husband",      1,    1,    __husband },
  { "incr",         1,    1,    __incr },
  { "index",        3,    3,    __index },
  { "indi",         1,    1,    __indi },
  { "indiset",      1,    1,    __indiset },
  { "inode",        1,    1,    __inode },
  { "insert",       3,    3,    __insert },
  { "inset",        2,    2,    __inset },
  { "intersect",    2,    2,    __intersect },
  { "isnull",       1,    1,    __isnull },
  { "key",          1,    2,    __key },
  { "keysort",      1,    1,    __keysort },
  { "lastchild",    1,    1,    __lastchild },
  { "lastfam",      0,    0,    __lastfam },
  { "lastindi",     0,    0,    __lastindi },
  { "le",           2,    2,    __le },
  { "length",       1,    1,    __length },
  { "lengthset",    1,    1,    __lengthset },
//{ "linemode",     0,    0,    __linemode },
  { "list",         1,    1,    __list },
  { "lock",         1,    1,    __noop },
  { "long",         1,    1,    __long },
  { "lookup",       2,    2,    __lookup },
  { "lower",        1,    1,    __lower },
  { "lt",           2,    2,    __lt },
  { "male",         1,    1,    __male },
  { "marriage",     1,    1,    __marriage },
  { "menuchoose",   1,    2,    __menuchoose },
  { "mod",          2,    2,    __mod },
  { "monthformat",  1,    1,    __monthformat },
  { "mother",       1,    1,    __mother },
  { "mul",          2,    CC,    __mul },
  { "name",         1,    2,    __name },
  { "namesort" ,    1,    1,    __namesort },
  { "nchildren",    1,    1,    __nchildren },
  { "ne",           2,    2,    __ne },
  { "neg",          1,    1,    __neg },
  { "nestr",        2,    2,    __strcmp },
  { "newfile",      0,    2,    __newfile },
  { "nextfam",      1,    1,    __nextfam },
  { "nextindi",     1,    1,    __nextindi },
  { "nextsib",      1,    1,    __nextsib },
  { "nfamilies",    1,    1,    __nfamilies },
  { "nl",           0,    0,    __nl },
  { "not",          1,    1,    __not },
  { "nspouses",     1,    1,    __nspouses },
  { "or",           2,    CC,    __or },
  { "ord",          1,    1,    __ord },
  { "outfile",      0,    0,    __outfile },
  { "pagemode",     2,    2,    __pagemode },
  { "pageout",      0,    0,    __pageout },
  { "parent",       1,    1,    __parent },
  { "parents",      1,    1,    __parents },
  { "parentset",    1,    1,    __parentset },
  { "place",        1,    1,    __place },
  { "pn",           2,    2,    __pn },  // Outputs pronouns
  { "pop",          1,    1,    __removeFirst },
  { "pos",          2,    2,    __pos },
  { "prepend",      2,    2,    __prepend },
  { "prevfam",      1,    1,    __prevfam },
  { "previndi",     1,    1,    __previndi },
  { "prevsib",      1,    1,    __prevsib },
  { "print",        1,    CC,   __print },
  { "push",         2,    2,    __prepend },
  { "qt",           0,    0,    __qt },
  { "reference",    1,    1,    __reference },
  { "removeFirst",  1,    1,    __removeFirst },
  { "removeLast",   1,    1,    __removeLast },
  { "requeue",      2,    2,    __append },
  { "rjustify",     2,    2,    __rjustify },
  { "roman",        1,    1,    __roman },
  { "root",         1,    1,    __root },  // Not needed as in LL; now walks up the Gedcom tree.
  { "row",          1,    1,    __row },
  { "save",         1,    1,    __save },
  { "savenode",     1,    1,    __savenode },
  { "set",          2,    2,    __set },
  { "setel",        3,    3,    __setel },
  { "sex",          1,    1,    __sex },
  { "short",        1,    1,    __short },  // Short form of an event.
  { "showframe",    0,    0,    __SHOWFRAME },
  { "showstack",    0,    0,    __SHOWSTACK },
  { "sibling",      1,    1,    __sibling },
  { "siblingset",   1,    1,    __siblingset },
  { "soundex",      1,    1,    __soundex },
  { "sp",           0,    0,    __space },
  { "spouseset",    1,    1,    __spouseset },
  { "stddate",      1,    1,    __stddate },
  { "strcmp",       2,    2,    __strcmp },
  { "strconcat",    2,    CC,    __concat },
  { "strlen",       1,    1,    __strlen },
  { "strsave",      1,    1,    __save },
  { "strsoundex",   1,    1,    __strsoundex },
  { "strtoint",     1,    1,    __strtoint },
  { "sub",          2,    2,    __sub },
  { "substring",    3,    3,    __substring },
  { "surname",      1,    1,    __surname },
//{ "system",       1,    1,    __system },
  { "table",        1,    1,    __table },
  { "tag",          1,    1,    __tag },
  { "title",        1,    1,    __title },
  { "trim",         2,    2,    __trim },
  { "trimname",     2,    2,    __trimname },
  { "typeof",       1,    1,    __TYPEOF },
  { "union",        2,    2,    __union },
  { "uniqueset",    1,    1,    __uniqueset },
  { "unlock",       1,    1,    __noop },
  { "upper",        1,    1,    __upper },
  { "value",        1,    1,    __value },
  { "valuesort",    1,    1,    __valuesort },
  { "version",      0,    0,    __version },
  { "wife",         1,    1,    __wife },
  { "xref",         1,    1,    __xref },
  { "year",         1,    1,    __year },
};

int nobuiltins = sizeof(builtIns)/sizeof(builtIns[0]);
